# Generated by Django 4.2.1 on 2024-02-20 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('district', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(max_length=6, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('fssai_no', models.CharField(max_length=14, null=True)),
                ('is_approved', models.BooleanField(default=False, null=True)),
                ('auth_token', models.CharField(max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('year', models.IntegerField(null=True)),
                ('is_validated', models.BooleanField(default=False, null=True)),
                ('last_inspected_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
